# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.istio.extensions.v1alpha1 import TrafficExtension as _Resource22
    from cloudcoil.models.istio.extensions.v1alpha1 import WasmPlugin as _Resource26
    from cloudcoil.models.istio.networking.v1 import DestinationRule as _Resource2
    from cloudcoil.models.istio.networking.v1 import Gateway as _Resource6
    from cloudcoil.models.istio.networking.v1 import ServiceEntry as _Resource14
    from cloudcoil.models.istio.networking.v1 import Sidecar as _Resource17
    from cloudcoil.models.istio.networking.v1 import VirtualService as _Resource23
    from cloudcoil.models.istio.networking.v1 import WorkloadEntry as _Resource27
    from cloudcoil.models.istio.networking.v1 import WorkloadGroup as _Resource30
    from cloudcoil.models.istio.networking.v1alpha3 import DestinationRule as _Resource3
    from cloudcoil.models.istio.networking.v1alpha3 import EnvoyFilter as _Resource5
    from cloudcoil.models.istio.networking.v1alpha3 import Gateway as _Resource7
    from cloudcoil.models.istio.networking.v1alpha3 import ServiceEntry as _Resource15
    from cloudcoil.models.istio.networking.v1alpha3 import Sidecar as _Resource18
    from cloudcoil.models.istio.networking.v1alpha3 import VirtualService as _Resource24
    from cloudcoil.models.istio.networking.v1alpha3 import WorkloadEntry as _Resource28
    from cloudcoil.models.istio.networking.v1alpha3 import WorkloadGroup as _Resource31
    from cloudcoil.models.istio.networking.v1beta1 import DestinationRule as _Resource4
    from cloudcoil.models.istio.networking.v1beta1 import Gateway as _Resource8
    from cloudcoil.models.istio.networking.v1beta1 import ProxyConfig as _Resource11
    from cloudcoil.models.istio.networking.v1beta1 import ServiceEntry as _Resource16
    from cloudcoil.models.istio.networking.v1beta1 import Sidecar as _Resource19
    from cloudcoil.models.istio.networking.v1beta1 import VirtualService as _Resource25
    from cloudcoil.models.istio.networking.v1beta1 import WorkloadEntry as _Resource29
    from cloudcoil.models.istio.networking.v1beta1 import WorkloadGroup as _Resource32
    from cloudcoil.models.istio.security.v1 import AuthorizationPolicy as _Resource0
    from cloudcoil.models.istio.security.v1 import PeerAuthentication as _Resource9
    from cloudcoil.models.istio.security.v1 import RequestAuthentication as _Resource12
    from cloudcoil.models.istio.security.v1beta1 import AuthorizationPolicy as _Resource1
    from cloudcoil.models.istio.security.v1beta1 import PeerAuthentication as _Resource10
    from cloudcoil.models.istio.security.v1beta1 import RequestAuthentication as _Resource13
    from cloudcoil.models.istio.telemetry.v1 import Telemetry as _Resource20
    from cloudcoil.models.istio.telemetry.v1alpha1 import Telemetry as _Resource21

_MODELS = {
    ("AuthorizationPolicy", "security.istio.io/v1"): (
        "cloudcoil.models.istio.security.v1",
        "AuthorizationPolicy",
    ),
    ("AuthorizationPolicy", "security.istio.io/v1beta1"): (
        "cloudcoil.models.istio.security.v1beta1",
        "AuthorizationPolicy",
    ),
    ("DestinationRule", "networking.istio.io/v1"): (
        "cloudcoil.models.istio.networking.v1",
        "DestinationRule",
    ),
    ("DestinationRule", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "DestinationRule",
    ),
    ("DestinationRule", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "DestinationRule",
    ),
    ("EnvoyFilter", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "EnvoyFilter",
    ),
    ("EnvoyFilter", ""): ("cloudcoil.models.istio.networking.v1alpha3", "EnvoyFilter"),
    ("Gateway", "networking.istio.io/v1"): ("cloudcoil.models.istio.networking.v1", "Gateway"),
    ("Gateway", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "Gateway",
    ),
    ("Gateway", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "Gateway",
    ),
    ("PeerAuthentication", "security.istio.io/v1"): (
        "cloudcoil.models.istio.security.v1",
        "PeerAuthentication",
    ),
    ("PeerAuthentication", "security.istio.io/v1beta1"): (
        "cloudcoil.models.istio.security.v1beta1",
        "PeerAuthentication",
    ),
    ("ProxyConfig", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "ProxyConfig",
    ),
    ("ProxyConfig", ""): ("cloudcoil.models.istio.networking.v1beta1", "ProxyConfig"),
    ("RequestAuthentication", "security.istio.io/v1"): (
        "cloudcoil.models.istio.security.v1",
        "RequestAuthentication",
    ),
    ("RequestAuthentication", "security.istio.io/v1beta1"): (
        "cloudcoil.models.istio.security.v1beta1",
        "RequestAuthentication",
    ),
    ("ServiceEntry", "networking.istio.io/v1"): (
        "cloudcoil.models.istio.networking.v1",
        "ServiceEntry",
    ),
    ("ServiceEntry", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "ServiceEntry",
    ),
    ("ServiceEntry", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "ServiceEntry",
    ),
    ("Sidecar", "networking.istio.io/v1"): ("cloudcoil.models.istio.networking.v1", "Sidecar"),
    ("Sidecar", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "Sidecar",
    ),
    ("Sidecar", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "Sidecar",
    ),
    ("Telemetry", "telemetry.istio.io/v1"): ("cloudcoil.models.istio.telemetry.v1", "Telemetry"),
    ("Telemetry", "telemetry.istio.io/v1alpha1"): (
        "cloudcoil.models.istio.telemetry.v1alpha1",
        "Telemetry",
    ),
    ("TrafficExtension", "extensions.istio.io/v1alpha1"): (
        "cloudcoil.models.istio.extensions.v1alpha1",
        "TrafficExtension",
    ),
    ("TrafficExtension", ""): ("cloudcoil.models.istio.extensions.v1alpha1", "TrafficExtension"),
    ("VirtualService", "networking.istio.io/v1"): (
        "cloudcoil.models.istio.networking.v1",
        "VirtualService",
    ),
    ("VirtualService", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "VirtualService",
    ),
    ("VirtualService", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "VirtualService",
    ),
    ("WasmPlugin", "extensions.istio.io/v1alpha1"): (
        "cloudcoil.models.istio.extensions.v1alpha1",
        "WasmPlugin",
    ),
    ("WasmPlugin", ""): ("cloudcoil.models.istio.extensions.v1alpha1", "WasmPlugin"),
    ("WorkloadEntry", "networking.istio.io/v1"): (
        "cloudcoil.models.istio.networking.v1",
        "WorkloadEntry",
    ),
    ("WorkloadEntry", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "WorkloadEntry",
    ),
    ("WorkloadEntry", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "WorkloadEntry",
    ),
    ("WorkloadGroup", "networking.istio.io/v1"): (
        "cloudcoil.models.istio.networking.v1",
        "WorkloadGroup",
    ),
    ("WorkloadGroup", "networking.istio.io/v1alpha3"): (
        "cloudcoil.models.istio.networking.v1alpha3",
        "WorkloadGroup",
    ),
    ("WorkloadGroup", "networking.istio.io/v1beta1"): (
        "cloudcoil.models.istio.networking.v1beta1",
        "WorkloadGroup",
    ),
}


@overload
def get_model(
    kind: Literal["AuthorizationPolicy"], *, api_version: Literal["security.istio.io/v1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["AuthorizationPolicy"], *, api_version: Literal["security.istio.io/v1beta1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["DestinationRule"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["DestinationRule"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["DestinationRule"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["EnvoyFilter"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["EnvoyFilter"], *, api_version: Literal[""] = ""
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["Gateway"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["Gateway"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["Gateway"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["PeerAuthentication"], *, api_version: Literal["security.istio.io/v1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["PeerAuthentication"], *, api_version: Literal["security.istio.io/v1beta1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["ProxyConfig"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["ProxyConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["RequestAuthentication"], *, api_version: Literal["security.istio.io/v1"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["RequestAuthentication"], *, api_version: Literal["security.istio.io/v1beta1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["ServiceEntry"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["ServiceEntry"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["ServiceEntry"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource16]: ...


@overload
def get_model(
    kind: Literal["Sidecar"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["Sidecar"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["Sidecar"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource19]: ...


@overload
def get_model(
    kind: Literal["Telemetry"], *, api_version: Literal["telemetry.istio.io/v1"]
) -> type[_Resource20]: ...


@overload
def get_model(
    kind: Literal["Telemetry"], *, api_version: Literal["telemetry.istio.io/v1alpha1"]
) -> type[_Resource21]: ...


@overload
def get_model(
    kind: Literal["TrafficExtension"], *, api_version: Literal["extensions.istio.io/v1alpha1"]
) -> type[_Resource22]: ...


@overload
def get_model(
    kind: Literal["TrafficExtension"], *, api_version: Literal[""] = ""
) -> type[_Resource22]: ...


@overload
def get_model(
    kind: Literal["VirtualService"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource23]: ...


@overload
def get_model(
    kind: Literal["VirtualService"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource24]: ...


@overload
def get_model(
    kind: Literal["VirtualService"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource25]: ...


@overload
def get_model(
    kind: Literal["WasmPlugin"], *, api_version: Literal["extensions.istio.io/v1alpha1"]
) -> type[_Resource26]: ...


@overload
def get_model(
    kind: Literal["WasmPlugin"], *, api_version: Literal[""] = ""
) -> type[_Resource26]: ...


@overload
def get_model(
    kind: Literal["WorkloadEntry"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource27]: ...


@overload
def get_model(
    kind: Literal["WorkloadEntry"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource28]: ...


@overload
def get_model(
    kind: Literal["WorkloadEntry"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource29]: ...


@overload
def get_model(
    kind: Literal["WorkloadGroup"], *, api_version: Literal["networking.istio.io/v1"]
) -> type[_Resource30]: ...


@overload
def get_model(
    kind: Literal["WorkloadGroup"], *, api_version: Literal["networking.istio.io/v1alpha3"]
) -> type[_Resource31]: ...


@overload
def get_model(
    kind: Literal["WorkloadGroup"], *, api_version: Literal["networking.istio.io/v1beta1"]
) -> type[_Resource32]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
